[phases.setup]
nixPkgs = ["python3", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdocs build"]

[start]
cmd = "python3 -m http.server $PORT --directory site"

